[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.22", "pybind11-stubgen","pyarrow>=10.0.0,<11"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["python/tests"]

[tool.cibuildwheel]
build-verbosity = 0
before-all = [
    "yum install -y bzip2-devel libffi-devel zlib-devel wget perl-IPC-Cmd perl-Test-Simple",
]

manylinux-x86_64-image = "manylinux_2_24"
environment = "CMAKE_ARGS_F=/tmp/cmake_args"
before-build = [
    "rm {project}/CMakeCache.txt {project}/build {project}/CMakeFiles.txt {project}/_deps || true",
    "wget -q https://github.com/gurgenyegoryan/ustore-conan/releases/download/v0.1.4/miniconda.tar.gz",
    "tar -xzf miniconda.tar.gz -C ~/",
    "export PATH='~/miniconda3/bin:/usr/bin:$PATH'",
    "~/miniconda3/bin/conda init",
    "source ~/.bashrc || true",
    "pip install pyarrow==10.0.1 auditwheel conan==1.57.0 cmake",
    "export CC=~/miniconda3/bin/gcc",
    "export CXX=~/miniconda3/bin/g++",
    "export LD_LIBRARY_PATH=~/miniconda3/lib:~/miniconda3/x86_64-conda-linux-gnu/sysroot/usr/lib64:$LD_LIBRARY_PATH",
    "export LD_LIBRARY_PATH=~/miniconda3/lib/python3.11/site-packages/pyarrow:/usr/bin:$LD_LIBRARY_PATH",
    "wget -q https://github.com/gurgenyegoryan/ustore-conan/releases/download/v0.1.7/arrow_10_0_0.tar.gz",
    "tar -xzf {project}/arrow_10_0_0.tar.gz -C {project}/",
    "rm -rf {project}/arrow_10_0_0.tar.gz",
    "conan profile new --detect default",
    "conan profile update settings.compiler=gcc default",
    "conan profile update settings.compiler.libcxx=libstdc++11 default",
    "wget -q https://github.com/gurgenyegoryan/ustore-conan/releases/download/v0.1.7/ustore_deps_x86_linux.tar.gz",
    "tar -xzf {project}/ustore_deps_x86_linux.tar.gz -C ~/.conan",
    "rm -rf {project}/ustore_deps_x86_linux.tar.gz",
    "conan install ustore_deps/0.12.1@unum/x86_linux -g cmake -s compiler.version=11",
    #"conan profile update settings.compiler.version=11 default",
    "export PYST=$(python -c 'import site; print(site.getsitepackages()[0])')",
    "echo \"-DCMAKE_BUILD_TYPE=Release -DPYARROW_DIR=${PYST}/pyarrow/\" > ${CMAKE_ARGS_F}",
    "mkdir -p build/ustore",
]

skip = ["*musllinux*", "*i686*", "pp*", "cp36-*"]

# test-command = "pytest {project}/python/tests/"
# test-requires = ["pandas"]
# test-extras = ["test"]

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"