name: Pre-Release

on:
  push:
    branches: ["main-dev"]

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  BUILD_TYPE: Release


jobs:
  versioning:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        ref: 'main-dev'
    - uses: actions/setup-node@v3
    - run: cp .github/workflows/package.json . && npm install && npx semantic-release
  
  
  build_ustore:
    name: Build Libraries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'
          
      - run: git submodule update --init --recursive

      - name: Prepare CMake, Conan and PyArrow
        run: python -m pip install --force-reinstall numpy pyarrow cmake conan==1.60.1

      - name: Install Conan dependencies
        run: |
          wget -q https://github.com/unum-cloud/ustore-deps/releases/download/v0.1.3/ustore_deps_x86_linux.tar.gz
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          tar -xzf ./ustore_deps_x86_linux.tar.gz -C ~/.conan
          conan install ustore_deps/0.12.1@unum/x86_linux -g cmake -s compiler.version=11
          rm -rf ./ustore_deps_x86_linux.tar.gz

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
                -DUSTORE_BUILD_ENGINE_UCSET=1 \
                -DUSTORE_BUILD_ENGINE_LEVELDB=1 \
                -DUSTORE_BUILD_ENGINE_ROCKSDB=1 \
                -DUSTORE_BUILD_API_FLIGHT=1 \
                -DUSTORE_BUILD_TESTS=1 \
                -DUSE_CONAN=1 \
                -B ./build_release .
                
      - name: Build   
        run: make -j 4 -C ./build_release

      - name: Upload Binaries
        uses: actions/upload-artifact@v3.1.1
        with:
          name: binaries
          path: build_release/build/bin/*


  test_cpp:
    name: Test C++
    runs-on: ubuntu-latest
    needs: build_ustore
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: binaries

      - name: Change permissions
        run: chmod +x /home/runner/work/ustore/ustore/*
      
      - name: Run embeded tests
        run: |
          mkdir -p ./tmp/ustore/
          export USTORE_TEST_PATH="./tmp/"
          for test in $(ls /home/runner/work/ustore/ustore/*test_units_ustore_embedded*); do
            echo -e "------ \e[93mRunning $test\e[0m ------"
            timeout -v --kill-after=5 300 $test
          done

      - name: Run Arrow Flight tests
        run: /home/runner/work/ustore/ustore/test_units_ustore_flight_client


  test_python:
    name: Test Python 3.9 & 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'

      - name: Prepare CMake, Conan and PyArrow
        run: python -m pip install --force-reinstall numpy pyarrow cmake conan==1.60.1

      - name: Build Wheels
        run: |
          pip install cibuildwheel twine
          CIBW_BUILD="cp39-*" cibuildwheel --platform linux
          CIBW_BUILD="cp310-*" cibuildwheel --platform linux
  

  test_java:
    name: Test Java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'

      - name: Prepare CMake, Conan and PyArrow
        run: python -m pip install --force-reinstall numpy pyarrow cmake conan==1.60.1
      
      - name: Install JDK
        run: |
          sudo apt update
          sudo apt install default-jdk -y
      
      - name: Install Conan dependencies
        run: |
          wget -q https://github.com/unum-cloud/ustore-deps/releases/download/v0.1.3/ustore_deps_x86_linux.tar.gz
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          tar -xzf ./ustore_deps_x86_linux.tar.gz -C ~/.conan
          conan install ustore_deps/0.12.1@unum/x86_linux -g cmake -s compiler.version=11
          rm -rf ./ustore_deps_x86_linux.tar.gz

      - name: Test Java
        run: |
          mkdir -p ./tmp
          export USTORE_TEST_PATH="./tmp/"
          sed -i 's/make -j/make -j4/' /home/runner/work/ustore/ustore/java/pack.sh
          export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
          bash /home/runner/work/ustore/ustore/java/pack.sh